wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    code_path: code/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.12
    start_time: 1741696053
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 14
      - 16
      4: 3.10.12
      5: 0.12.21
      8:
      - 5
align:
  desc: null
  value: Alignment.CHAOTIC
batch_size:
  desc: null
  value: 128
character:
  desc: null
  value: ran-orc-cha
checkpoints_path:
  desc: null
  value: ./checkpoints/inverse_bc-v0/inverse_bc-ran-orc-cha-ran-orc-cha-f86cfbde
clip_grad_norm:
  desc: null
  value: null
data_mode:
  desc: null
  value: compressed
data_path:
  desc: null
  value: /code/NetHack-Research/data/processed/hdf5_data/
eval_episodes:
  desc: null
  value: 25
eval_every:
  desc: null
  value: 5000
eval_processes:
  desc: null
  value: 8
eval_seed:
  desc: null
  value: 52
group:
  desc: null
  value: inverse_bc-v0
inverse_model_lr:
  desc: null
  value: 0.0001
inverse_model_path:
  desc: null
  value: null
inverse_model_weight:
  desc: null
  value: 1.0
learning_rate:
  desc: null
  value: 0.0003
name:
  desc: null
  value: inverse_bc-ran-orc-cha-ran-orc-cha-f86cfbde
project:
  desc: null
  value: NetHack
race:
  desc: null
  value: Race.ORC
render_processes:
  desc: null
  value: 8
rnn_dropout:
  desc: null
  value: 0.0
rnn_hidden_dim:
  desc: null
  value: 1024
rnn_layers:
  desc: null
  value: 1
role:
  desc: null
  value: Role.RANGER
seq_len:
  desc: null
  value: 8
size:
  desc: null
  value: small
train_inverse_model:
  desc: null
  value: true
train_seed:
  desc: null
  value: 42
update_steps:
  desc: null
  value: 25000
use_difference_vector:
  desc: null
  value: false
use_inverse_model:
  desc: null
  value: true
use_prev_action:
  desc: null
  value: true
version:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
