align: NEUTRAL
batch_size: 256
character: arc-hum-neu
checkpoints_path: ./checkpoints/inverse_bc-v0/inverse_bc-arc-hum-neu-arc-hum-neu-5a8847e1
clip_grad_norm: null
data_mode: compressed
data_path: /code/NetHack-Research/data/processed/hdf5_data/
eval_episodes: 25
eval_every: 5000
eval_processes: 8
eval_seed: 52
group: inverse_bc-v0
inverse_model_lr: 0.0001
inverse_model_path: null
inverse_model_weight: 1.0
learning_rate: 0.0003
name: inverse_bc-arc-hum-neu-arc-hum-neu-5a8847e1
project: NetHack
race: HUMAN
render_processes: 8
rnn_dropout: 0.0
rnn_hidden_dim: 1024
rnn_layers: 1
role: ARCHEOLOGIST
seq_len: 8
size: small
train_inverse_model: true
train_seed: 42
update_steps: 25000
use_difference_vector: false
use_inverse_model: true
use_prev_action: true
version: 0
weight_decay: 0.0
